const types = {
	SUBMIT_PARTIAL_FORM :     'SUBMIT_PARTIAL_FORM',
	REQUEST_INITIATION  :     'REQUEST_INITIATION',
	REQUEST_COMPLETED   :     'REQUEST_COMPLETED',
	PROGRESS_UPDATE     :     'PROGRESS_UPDATE',
	RESET_USER_STATE    :     'RESET_USER_STATE',
	AGENT_ROLE          :     'AGENT_ROLE',
	PATIENT_ROLE		: 	  'PATIENT_ROLE',
	DOCTOR_ROLE			:  	  'DOCTOR_ROLE'
};

export default types;