const types = {
	SUBMIT_PARTIAL_FORM :     'SUBMIT_PARTIAL_FORM',
	REQUEST_INITIATION  :     'REQUEST_INITIATION',
	REQUEST_COMPLETED   :     'REQUEST_COMPLETED',
	PROGRESS_UPDATE     :     'PROGRESS_UPDATE',
	RESET_USER_STATE    :     'RESET_USER_STATE',
	AGENT_ROLE          :     'AGENT_ROLE',
	PATIENT_ROLE		: 	  'PATIENT_ROLE',
	DOCTOR_ROLE			:  	  'DOCTOR_ROLE',
	SET_LAN			    :  	  'SET_LAN',
	SET_PATIENT_INFO	:     'SET_PATINET_INFO',
	SET_ATTORNEY_INFO	:     'SET_ATTORNEY_INFO',
	SET_INSURANCE_INFO	:     'SET_INSURANCE_INFO',
	SET_NOTE_INFO		:     'SET_NOTE_INFO',
	SET_DOCTORS			:	  'SET_DOCTORS'
};

export default types;